on: [push, pull_request]

name: Clippy

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          components: clippy
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # TODO: For now, allow clippy::erasing_op
          # TODO: Enable clippy on examples via `--examples`
          args: --target thumbv7em-none-eabihf --features=rt,stm32f746 -- --allow clippy::erasing_op
